### ISSUE TITLE
Proposal: Merge bootstrap into ping monitoring node?

### ISSUE THREAD

**Issue by t-lin** [Multi-Tier-Cloud/bootstrap-node#3]
@andrew-cc-chen @henryxu1997 @hivanco @michaelweiyuzhao 
Just want to get you guys' opinions and see if anyone has reasons to oppose this change? It would decrease the # of repos and merge the functionality.
- Since the ping monitoring is currently strategically placed at points where traffic must go through (e.g. default gateway / router), it serves as an ideal location to collect metrics from.
- It's also a logical assumption that peers could look for bootstraps by attempting to connect to their default gateway.

**Comment by mwyzhao** [comment]
I think we could integrate the option of reading a key from disk into `NewNode()` just for flexibility's sake. In that case, the only difference between the bootstrap and any other node is the master bootstrap list we keep.
